# Generated by Django 4.2.4 on 2023-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ovqat nomi')),
                ('price', models.IntegerField(verbose_name='Narx')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='muallif',
            field=models.CharField(default=2000, max_length=50, verbose_name='Muallif'),
            preserve_default=False,
        ),
    ]
